unit cartbook;

(* This file is generated by makeoopenbook - do not edit manually. *)

interface

uses board, globals;

const
    BankSize = 100;
    OpeningPositions = 87;

type
    TBookEntry = record
        compressedBoard: TCompressedBoard;
        bookMoves: TBookMoves
    end;
    TOpeningBook = array [0..BankSize - 1] of TBookEntry;

function getMove (n: integer): TBookEntry;

implementation

function getMove0 (n: integer): TBookEntry;
    procedure book_0; external '../book/book0.dat';
    begin
        result := TOpeningBook (addr(book_0)) [n]
    end;

function getMove (n: integer): TBookEntry;
    begin
        case n div BankSize of
             0: result := getMove0 (n mod BankSize)
        end
    end;

end.
