program openbook;

{$MODE DELPHI}
{$UNITPATH ../sp}

uses readbook, board, logger, math;

const
    BankSize = 165;

procedure printOpenings;
    var
        i, j: integer;
    begin
        writeln ('Size of board is ', sizeof (TCompressedBoard));
        writeln ('Opening moves: ', posCount, ' positions, max moves is ', maxPosMoves);
        for i := 1 to posCount do
            begin
                write (i:4, ' ', hexstr (openings [i].hash, 16), ' ');
                write ('Moves: ', openings [i].count, ' ');
                for j := 1 to openings [i].count do
                    begin
                        printMove (output, openings [i].nextMoves [j]);
                        write ('(', openings [i].moveWeights [j], ') ')
                    end;
                writeln
            end
    end;
    
procedure saveOpenings;
    var 
        maxWeight, scale, count, i, j: integer;
        s: string;
        f: file;
        g: text;
        m: uint16;
    begin
        count := 0;
        assign (g, 'cartbook.pas');
        rewrite (g);
        
        writeln (g, 'unit cartbook;');
        writeln (g);
        writeln (g, '(* This file is generated by makeoopenbook - do not edit manually. *)');
        writeln (g);
        writeln (g, 'interface');
        writeln (g);
        writeln (g, 'uses board, globals;');
        writeln (g);
        writeln (g, 'const');
        writeln (g, '    BankSize = ', bankSize, ';');
        writeln (g, '    OpeningPositions = ', posCount, ';');
        writeln (g);
        writeln (g, 'type');
        writeln (g, '    TBookEntry = record');
        writeln (g, '        hash: uint64;');
        writeln (g, '        bookMoves: TBookMoves');
        writeln (g, '    end;');
        writeln (g, '    TOpeningBook = array [0..BankSize - 1] of TBookEntry;');
        writeln (g);
        writeln (g, 'function getMove (n: integer): TBookEntry;');
        writeln (g);
        writeln (g, 'implementation');
        writeln (g);
        
        while count * bankSize < posCount do
            begin
                str (count, s);
                assign (f, 'book' + s + '.dat');
                rewrite (f, 1);
                for i := succ (bankSize * count) to min (posCount, bankSize * succ (count)) do
                    begin
                        openings [i].hash := swapEndian (openings [i].hash);
                        blockwrite (f, openings [i].hash, sizeof (uint64));
                        openings [i].hash := swapEndian (openings [i].hash);
                        
                        maxWeight := 0;
                        for j := 1 to maxMoves do
                            if j <= openings [i].count then
                                maxWeight := max (maxWeight, openings [i].moveWeights [j]);
                        if maxWeight > 15 then
                            begin
                                scale := succ (maxWeight div 16);
                                for j := 1 to maxMoves do
                                    if j <= openings [i].count then
                                        openings [i].moveWeights [j] := max (1, openings [i].moveWeights [j] div scale)
                            end;
                                    
                        for j := 1 to maxMoves do
                            begin
                                if j <= openings [i].count then
                                    m := (openings [i].nextMoves [j].startSq shl 6) or openings [i].nextMoves [j].endSq or openings [i].moveWeights [j] shl 12
                                else
                                    m := 0;
                                m := swapEndian (m);
                                blockwrite (f, m, sizeof (m))
                            end
                    end;
                close (f);
                writeln (g, 'function getMove' + s + ' (n: integer): TBookEntry;');
                writeln (g, '    procedure book_' + s + '; external ''../book/book' + s + '.dat'';');
                writeln (g, '    begin');
                writeln (g, '        result := TOpeningBook (addr(book_' + s + ')) [n]');
                writeln (g, '    end;');
                writeln (g);
                inc (count)
            end;
            
        writeln (g, 'function getMove (n: integer): TBookEntry;');
        writeln (g, '    begin');
        writeln (g, '        case n div BankSize of');
        for i := 0 to pred (count) do
            begin
                write (g, i:14, ': result := getMove', i,  ' (n mod BankSize)');
                if i <> pred (count) then
                    write (g, ';');
                writeln (g)
            end;
        writeln (g, '        end');
        writeln (g, '    end;');
        writeln (g);
        writeln (g, 'end.');
        close (g)
    end;

    
begin
    writeln ('Analyzing ', ParamStr (1));
    loadOpeningBook (ParamStr (1));
    saveOpenings;
    printOpenings
end.
    
